name: Deploy Main Branch
on:
  push:
    branches: ["main"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # download repo code in github runner
      - name: Checkout repository in runner
        uses: actions/checkout@v3

      # copy repo files to server
      - name: Copy repo files to VPS server from runner
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "./,!node_modules,!.cache"
          target: "/home/ubuntu/applicator_view/backend/applicator-view"

      # start app on server
      - name: Start App on VPS server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          script: |
            ls -a
            cd /home/ubuntu/applicator_view/backend/applicator-view
            npm install
            pm2 delete all
            pm2 start